package com.mycompany.calculadora;

import com.mycompany.calculadora.Calculadora;
import com.mycompany.calculadora.Calculadora;
import com.mycompany.calculadora.Calculadora;

/**
 *
 * @author julio
 */
public class CalcWind extends javax.swing.JFrame {
    Calculadora calc = new Calculadora();//Instancio
    /**
     * Creates new form CalcWind
     */
    public CalcWind() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTxtPantalla = new javax.swing.JTextField();
        jBtnCambioSigno = new javax.swing.JButton();
        jBtnNro0 = new javax.swing.JButton();
        jBtnComa = new javax.swing.JButton();
        jBtnTotal = new javax.swing.JButton();
        jBtnNro1 = new javax.swing.JButton();
        jBtnNro2 = new javax.swing.JButton();
        jBtnNro3 = new javax.swing.JButton();
        jBtnSuma = new javax.swing.JButton();
        jBtnNro4 = new javax.swing.JButton();
        jBtnNro5 = new javax.swing.JButton();
        jBtnNro6 = new javax.swing.JButton();
        jBtnResta = new javax.swing.JButton();
        jBtnNro7 = new javax.swing.JButton();
        jBtnNro8 = new javax.swing.JButton();
        jBtnNro9 = new javax.swing.JButton();
        jBtnMultiplicacion = new javax.swing.JButton();
        jBtnUnoSobre = new javax.swing.JButton();
        jBtnPow = new javax.swing.JButton();
        jBtnSqrt = new javax.swing.JButton();
        jBtnDivision = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jBtnClearAll = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jTxtPantalla.setBackground(new java.awt.Color(51, 51, 51));
        jTxtPantalla.setForeground(new java.awt.Color(255, 255, 255));
        jTxtPantalla.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTxtPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPantallaActionPerformed(evt);
            }
        });

        jBtnCambioSigno.setBackground(new java.awt.Color(102, 102, 102));
        jBtnCambioSigno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnCambioSigno.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCambioSigno.setText("+/-");
        jBtnCambioSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCambioSignoActionPerformed(evt);
            }
        });

        jBtnNro0.setBackground(new java.awt.Color(102, 102, 102));
        jBtnNro0.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNro0.setText("0");
        jBtnNro0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNro0ActionPerformed(evt);
            }
        });

        jBtnComa.setBackground(new java.awt.Color(102, 102, 102));
        jBtnComa.setForeground(new java.awt.Color(255, 255, 255));
        jBtnComa.setText(",");
        jBtnComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnComaActionPerformed(evt);
            }
        });

        jBtnTotal.setBackground(new java.awt.Color(204, 204, 204));
        jBtnTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtnTotal.setForeground(new java.awt.Color(0, 0, 0));
        jBtnTotal.setText("=");
        jBtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTotalActionPerformed(evt);
            }
        });

        jBtnNro1.setBackground(new java.awt.Color(102, 102, 102));
        jBtnNro1.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNro1.setText("1");
        jBtnNro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNro1ActionPerformed(evt);
            }
        });

        jBtnNro2.setBackground(new java.awt.Color(102, 102, 102));
        jBtnNro2.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNro2.setText("2");
        jBtnNro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNro2ActionPerformed(evt);
            }
        });

        jBtnNro3.setBackground(new java.awt.Color(102, 102, 102));
        jBtnNro3.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNro3.setText("3");
        jBtnNro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNro3ActionPerformed(evt);
            }
        });

        jBtnSuma.setBackground(new java.awt.Color(51, 51, 51));
        jBtnSuma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtnSuma.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSuma.setText("+");
        jBtnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSumaActionPerformed(evt);
            }
        });

        jBtnNro4.setBackground(new java.awt.Color(102, 102, 102));
        jBtnNro4.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNro4.setText("4");
        jBtnNro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNro4ActionPerformed(evt);
            }
        });

        jBtnNro5.setBackground(new java.awt.Color(102, 102, 102));
        jBtnNro5.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNro5.setText("5");
        jBtnNro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNro5ActionPerformed(evt);
            }
        });

        jBtnNro6.setBackground(new java.awt.Color(102, 102, 102));
        jBtnNro6.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNro6.setText("6");
        jBtnNro6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNro6ActionPerformed(evt);
            }
        });

        jBtnResta.setBackground(new java.awt.Color(51, 51, 51));
        jBtnResta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtnResta.setForeground(new java.awt.Color(255, 255, 255));
        jBtnResta.setText("-");
        jBtnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRestaActionPerformed(evt);
            }
        });

        jBtnNro7.setBackground(new java.awt.Color(102, 102, 102));
        jBtnNro7.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNro7.setText("7");
        jBtnNro7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNro7ActionPerformed(evt);
            }
        });

        jBtnNro8.setBackground(new java.awt.Color(102, 102, 102));
        jBtnNro8.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNro8.setText("8");
        jBtnNro8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNro8ActionPerformed(evt);
            }
        });

        jBtnNro9.setBackground(new java.awt.Color(102, 102, 102));
        jBtnNro9.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNro9.setText("9");
        jBtnNro9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNro9ActionPerformed(evt);
            }
        });

        jBtnMultiplicacion.setBackground(new java.awt.Color(51, 51, 51));
        jBtnMultiplicacion.setForeground(new java.awt.Color(255, 255, 255));
        jBtnMultiplicacion.setText("X");
        jBtnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMultiplicacionActionPerformed(evt);
            }
        });

        jBtnUnoSobre.setBackground(new java.awt.Color(51, 51, 51));
        jBtnUnoSobre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnUnoSobre.setForeground(new java.awt.Color(255, 255, 255));
        jBtnUnoSobre.setText("1/x");
        jBtnUnoSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUnoSobreActionPerformed(evt);
            }
        });

        jBtnPow.setBackground(new java.awt.Color(51, 51, 51));
        jBtnPow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnPow.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPow.setText("x²");
        jBtnPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPowActionPerformed(evt);
            }
        });

        jBtnSqrt.setBackground(new java.awt.Color(51, 51, 51));
        jBtnSqrt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnSqrt.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSqrt.setText("²√x");
        jBtnSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSqrtActionPerformed(evt);
            }
        });

        jBtnDivision.setBackground(new java.awt.Color(51, 51, 51));
        jBtnDivision.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtnDivision.setForeground(new java.awt.Color(255, 255, 255));
        jBtnDivision.setText("÷");
        jBtnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivisionActionPerformed(evt);
            }
        });

        jButton21.setBackground(new java.awt.Color(51, 51, 51));
        jButton21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("%");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(51, 51, 51));
        jButton22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("CE");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jBtnClearAll.setBackground(new java.awt.Color(51, 51, 51));
        jBtnClearAll.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnClearAll.setForeground(new java.awt.Color(255, 255, 255));
        jBtnClearAll.setText("C");
        jBtnClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearAllActionPerformed(evt);
            }
        });

        jBtnDelete.setBackground(new java.awt.Color(51, 51, 51));
        jBtnDelete.setForeground(new java.awt.Color(255, 255, 255));
        jBtnDelete.setText("⌫");
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtPantalla)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(jBtnClearAll, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtnUnoSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 65, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnPow, javax.swing.GroupLayout.PREFERRED_SIZE, 65, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtnNro7, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnNro8, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnNro9, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtnNro4, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnNro5, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnNro6, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtnNro1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnNro2, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnNro3, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtnCambioSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 65, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnNro0, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnComa, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jBtnSuma, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jBtnResta, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jBtnMultiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jBtnDivision, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jBtnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jTxtPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jBtnClearAll, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jBtnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnUnoSobre, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jBtnPow, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jBtnSqrt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jBtnDivision, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNro7, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jBtnNro8, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jBtnNro9, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jBtnMultiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNro4, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jBtnNro5, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jBtnNro6, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jBtnResta, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNro1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jBtnNro2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jBtnNro3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jBtnSuma, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCambioSigno, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jBtnNro0, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jBtnComa, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jBtnTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPantallaActionPerformed

    private void jBtnCambioSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCambioSignoActionPerformed
        // Boton cambio de signo
        calc.cambioSigno(jTxtPantalla.getText());
        jTxtPantalla.setText("");
    }//GEN-LAST:event_jBtnCambioSignoActionPerformed

    private void jBtnNro0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNro0ActionPerformed
        // Boton N°0
        calc.agregarNum(0);
        jTxtPantalla.setText(calc.getDigito());
    }//GEN-LAST:event_jBtnNro0ActionPerformed

    private void jBtnComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnComaActionPerformed
        // Boton coma
        calc.agregarNum('.');
        jTxtPantalla.setText(calc.getDigito());
    }//GEN-LAST:event_jBtnComaActionPerformed

    private void jBtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTotalActionPerformed
        // Total
        jTxtPantalla.setText(""+calc.resultadofinal(jTxtPantalla.getText()));
    }//GEN-LAST:event_jBtnTotalActionPerformed

    private void jBtnNro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNro1ActionPerformed
        // Boton N°1
        calc.agregarNum(1);
        jTxtPantalla.setText(calc.getDigito());
    }//GEN-LAST:event_jBtnNro1ActionPerformed

    private void jBtnNro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNro2ActionPerformed
        // Boton N°2
        calc.agregarNum(2);
        jTxtPantalla.setText(calc.getDigito());
    }//GEN-LAST:event_jBtnNro2ActionPerformed

    private void jBtnNro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNro3ActionPerformed
        // Boton N°3
        calc.agregarNum(3);
        jTxtPantalla.setText(calc.getDigito());
    }//GEN-LAST:event_jBtnNro3ActionPerformed

    private void jBtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSumaActionPerformed
        // Boton Suma
        calc.suma(jTxtPantalla.getText());
        jTxtPantalla.setText("");
    }//GEN-LAST:event_jBtnSumaActionPerformed

    private void jBtnNro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNro4ActionPerformed
        // Boton N°4
        calc.agregarNum(4);
        jTxtPantalla.setText(calc.getDigito());
    }//GEN-LAST:event_jBtnNro4ActionPerformed

    private void jBtnNro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNro5ActionPerformed
        // Boton N°5
        calc.agregarNum(5);
        jTxtPantalla.setText(calc.getDigito());
    }//GEN-LAST:event_jBtnNro5ActionPerformed

    private void jBtnNro6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNro6ActionPerformed
        // Boton N°6
        calc.agregarNum(6);
        jTxtPantalla.setText(calc.getDigito());
    }//GEN-LAST:event_jBtnNro6ActionPerformed

    private void jBtnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRestaActionPerformed
        // Boton Resta
        calc.resta(jTxtPantalla.getText());
        jTxtPantalla.setText("");
    }//GEN-LAST:event_jBtnRestaActionPerformed

    private void jBtnNro7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNro7ActionPerformed
        // Boton N°7
        calc.agregarNum(7);
        jTxtPantalla.setText(calc.getDigito());
    }//GEN-LAST:event_jBtnNro7ActionPerformed

    private void jBtnNro8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNro8ActionPerformed
        // Boton N°8
        calc.agregarNum(8);
        jTxtPantalla.setText(calc.getDigito());
    }//GEN-LAST:event_jBtnNro8ActionPerformed

    private void jBtnNro9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNro9ActionPerformed
        // Boton N°9
        calc.agregarNum(9);
        jTxtPantalla.setText(calc.getDigito());
    }//GEN-LAST:event_jBtnNro9ActionPerformed

    private void jBtnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMultiplicacionActionPerformed
        // Boton Multiplicacion
        calc.multiplicacion(jTxtPantalla.getText());
        jTxtPantalla.setText("");
    }//GEN-LAST:event_jBtnMultiplicacionActionPerformed

    private void jBtnUnoSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUnoSobreActionPerformed
        // Boton uno sobre
        calc.unoSobre(jTxtPantalla.getText());
        jTxtPantalla.setText("");
    }//GEN-LAST:event_jBtnUnoSobreActionPerformed

    private void jBtnPowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPowActionPerformed
        // Boton cuadradao
        calc.cuadrado(jTxtPantalla.getText());
        jTxtPantalla.setText("");
    }//GEN-LAST:event_jBtnPowActionPerformed

    private void jBtnSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSqrtActionPerformed
        // Boton raiz
        calc.raiz(jTxtPantalla.getText());
        jTxtPantalla.setText("");
    }//GEN-LAST:event_jBtnSqrtActionPerformed

    private void jBtnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivisionActionPerformed
        // Boton division
        calc.division(jTxtPantalla.getText());
        jTxtPantalla.setText("");
    }//GEN-LAST:event_jBtnDivisionActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // Boton porcentaje
        calc.porcentaje(jTxtPantalla.getText());
        jTxtPantalla.setText("");
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jBtnClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnClearAllActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcWind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcWind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcWind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcWind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcWind().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCambioSigno;
    private javax.swing.JButton jBtnClearAll;
    private javax.swing.JButton jBtnComa;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnDivision;
    private javax.swing.JButton jBtnMultiplicacion;
    private javax.swing.JButton jBtnNro0;
    private javax.swing.JButton jBtnNro1;
    private javax.swing.JButton jBtnNro2;
    private javax.swing.JButton jBtnNro3;
    private javax.swing.JButton jBtnNro4;
    private javax.swing.JButton jBtnNro5;
    private javax.swing.JButton jBtnNro6;
    private javax.swing.JButton jBtnNro7;
    private javax.swing.JButton jBtnNro8;
    private javax.swing.JButton jBtnNro9;
    private javax.swing.JButton jBtnPow;
    private javax.swing.JButton jBtnResta;
    private javax.swing.JButton jBtnSqrt;
    private javax.swing.JButton jBtnSuma;
    private javax.swing.JButton jBtnTotal;
    private javax.swing.JButton jBtnUnoSobre;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtPantalla;
    // End of variables declaration//GEN-END:variables
}
